Updated docs look and feel
axonops/documentation pull request #10
Opened 2024-04-09 19:36 UTC by brainJamStark

Added the AxonCloud docs.
Re-arranged navigation layout to cater for look and feel changes.

2024-04-10 09:42 UTC, rgooding requested changes

2024-04-10 09:42 UTC, rgooding commented on docs/editions/intro.md
> +All of this is underpinned by an efficient bi-directional protocol ensuring exception performance and scale.
exception -> exceptional

2024-04-10 09:42 UTC, rgooding commented on docs/editions/enterprise_edition.md
> +* Cloud or Self-Hosted, you choose.
These limits are for the free version, this needs updating for the Enterprise edition

2024-04-10 10:58 UTC, brainJamStark commented on docs/editions/intro.md
> +All of this is underpinned by an efficient bi-directional protocol ensuring exception performance and scale.
fixed

2024-04-10 10:58 UTC, brainJamStark commented on docs/editions/enterprise_edition.md
> +* Cloud or Self-Hosted, you choose.
Removed and updated. Please check

2024-04-10 11:26 UTC, rgooding approved these changes

2024-04-17 07:59 UTC, hshimizu approved these changes

2024-04-17 08:02 UTC, merged