Doc updates 2024 06 10
axonops/documentation pull request #15
Opened 2024-06-14 08:07 UTC by brainJamStark

2024-06-14 08:32 UTC, digiserg approved these changes

2024-06-14 08:52 UTC, rgooding commented on docs/overview/motivation.md
> +AxonOps has been developed and actively maintained by [axonops limited](https://axonops.com), a company providing managed services for Apache Cassandra™ and other modern distributed data technologies
`axonops limited` should probably be capitalised here as `AxonOps Limited`

2024-06-14 08:53 UTC, rgooding requested changes
Please see my comment below about captialisation of "AxonOps Limited"

2024-06-14 09:52 UTC, brainJamStark commented on docs/overview/motivation.md
> +AxonOps has been developed and actively maintained by [axonops limited](https://axonops.com), a company providing managed services for Apache Cassandra™ and other modern distributed data technologies
Fixed

2024-06-14 12:35 UTC, rgooding approved these changes

2024-06-17 09:13 UTC, hshimizu approved these changes
approved

2024-06-17 09:27 UTC, merged