added PITR to the docs
axonops/documentation pull request #22
Opened 2024-07-08 07:46 UTC by brainJamStark

2024-07-08 08:09 UTC, digiserg commented on docs/pitr/overview.md
> +In ```$CASSANDRA_HOME/conf/``` there is a file called ```commitlog-archiving.properties```.
in packaged installed cassandra, this will be `/etc/cassandra` - it may be worth adding it

2024-07-08 09:22 UTC, digiserg approved these changes

2024-07-08 11:16 UTC, rgooding requested changes
Some of the text in here needs tweaking for accuracy before this goes live. It's probably worth a discussion rather than writing it all in comments here.

2024-07-08 18:51 UTC, hshimizu approved these changes
approved

2024-07-09 08:40 UTC, rgooding approved these changes

2024-07-09 13:53 UTC, merged