updates in Logs&Events page
axonops/documentation pull request #8
Opened 2023-05-16 10:27 UTC by nolkhova

2023-05-16 11:31 UTC, rgooding commented on docs/monitoring/logsandevents/logsandevents.md
> +The logs and events are visible within AxonOps dashboard and Logs & Events tab allowing quick access to them without having to log in to the individual servers.
Could you please change "log in" to "login" here, I know it doesn't really matter but since this page is about logs it will reduce any possible confusion for the reader

2023-05-16 11:35 UTC, rgooding commented on docs/monitoring/logsandevents/logsandevents.md
> +For a free text search fulfill the ***content*** input with a keyword or search by regex expression via the `/<expression>/` pattern.
I would rephrase this, maybe something like this: "For a free text search enter a keyword in the **content** input or use the `/<expression>/` syntax to search by regular expression."

2023-05-16 11:44 UTC, rgooding requested changes
In addition to my comments below could you see if you can do something about the logsUI.png image? It doesn't display very well scaled down to fit in the page so maybe you need to take a screenshot of it with the window resized a bit smaller.

2023-05-16 11:44 UTC, rgooding commented on docs/monitoring/logsandevents/logsandevents.md
> +
This feels a little stuck on the end and out of place. Maybe it needs a sentence or two here explaining about searching by log level and maybe also a screenshot? I also think the instructions for setting up the debug level should be under a subheading so it appears in the page navigation on the right hand side

2023-05-18 07:57 UTC, nolkhova commented on docs/monitoring/logsandevents/logsandevents.md
> +The logs and events are visible within AxonOps dashboard and Logs & Events tab allowing quick access to them without having to log in to the individual servers.
changed

2023-05-18 07:57 UTC, nolkhova commented on docs/monitoring/logsandevents/logsandevents.md
> +For a free text search fulfill the ***content*** input with a keyword or search by regex expression via the `/<expression>/` pattern.
changed

2023-05-18 08:07 UTC, nolkhova commented on docs/monitoring/logsandevents/logsandevents.md
> +
done. I changed the heading order as well.

2023-05-18 10:05 UTC, rgooding approved these changes

2023-05-18 11:57 UTC, merged